[package]
name = "dygma_api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
dygma_focus = { version = "0.4", default-features = false, features = ["is_async"] }
tokio = { version = "1", features = ["full"] }