[font]
size = 13

[font.bold]
family = "Caskaydia Cove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Caskaydia Cove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Caskaydia Cove Nerd Font"
style = "Italic"

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 10
y = 10
